### ISSUE TITLE
🐞 Bug badge dernière version Docker 🐳 

### ISSUE THREAD

**Issue by Dougniel** [opt-nc/api-partenaires-mobilis#120]
![image](https://user-images.githubusercontent.com/39691264/155658308-da385202-5a0f-4abe-9e89-7b84ed0cca4c.png)

**Comment by Dougniel** [comment]
@adriens, j'avais déjà regardé et c'est plus compliqué, ce n'est pas de l'ordre du `quickfix`, il me semble que c'est lié aux signatures d'images qui positionnent des nouveaux tags qui font ce comportement là

**Comment by adriens** [comment]
Badge supprimé

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/158108996-290037e8-0caf-4051-ba85-a9a889ee9b2b.png)
