### ISSUE TITLE
Swagger indispo dans la version SpringNative

### ISSUE THREAD

**Issue by Dougniel** [opt-nc/api-partenaires-mobilis#125]
> Tu réussis à reproduire @Dougniel ❔

Effectivement je reproduis : 
<img width="1083" alt="image" src="https://user-images.githubusercontent.com/39691264/156306132-639fe811-413a-4f4d-90fb-682619f34a46.png">

Mais en version Docker Natif uniquement ! Alors c'est certainement un problème liée au passage en natif qui m'a échappée https://github.com/opt-nc/api-partenaires-mobilis/issues/4

_Originally posted by @Dougniel in https://github.com/opt-nc/GLIA/issues/253#issuecomment-1056384124_

**Comment by adriens** [comment]
AH MERDE :exclamation: 
Ca ça craint...y'a quoi à la place ?

**Comment by adriens** [comment]
:rofl: 
> As Swagger is already working with micronaut and quarkus, it should be possible in theory.

**Comment by adriens** [comment]
... à ajouter aux feedbacks sur l'expeérience native sur Spring Boot...

**Comment by Dougniel** [comment]
> AH MERDE ❗
> Ca ça craint...y'a quoi à la place ?

Je pense pouvoir m'en sortir en analysant la reflection Java avec l'outil mis à disposition par [SpringBoot/GraalVM](https://github.com/opt-nc/api-partenaires-mobilis/issues/4#issuecomment-1032299435)

**Comment by adriens** [comment]
Sinon, en attendant tu **peux modifier le katacoda en pullant le dernier tag** qui livre swagger au moins ça marchera

**Comment by adriens** [comment]
Juste pour fixer l'incident le temps de...

**Comment by Dougniel** [comment]
> Sinon, en attendant tu **peux modifier le katacoda en pullant le dernier tag** qui livre swagger au moins ça marchera

Je tente encore un coup, vu que j'ai commencé à regarder le soucis et si je n'y arrive pas dans la journée je ferais ça

**Comment by Dougniel** [comment]
Bug trouvé, il s'agit de Springdoc qui fait de la réflection sur une classe SpringBoot en douce.. du coup cette classe n'était pas incluse par Spring dans les classes sur lesquelles sont faite de la réflection Java et je ne l'ai pas vu [durant l'analyse](https://github.com/opt-nc/api-partenaires-mobilis/issues/4#issuecomment-1032299435) puisque les classes SpringBoot sont exclues, c'est en regardant [les sources Springboc](https://github.com/springdoc/springdoc-openapi/blob/a27af7c48473a44d4fcd28d5b5e5925b3098889c/springdoc-openapi-common/src/main/java/org/springdoc/core/DelegatingMethodParameter.java#L261) que je suis arrivé à cela, dans le `réflection-config.json`:

```json
...
  {
    "name": "org.springframework.core.MethodParameter",
    "allDeclaredFields":true
  }
...
''''

**Comment by adriens** [comment]
Je teste sur #253

**Comment by adriens** [comment]
Je viens de tester sur katacoda mais ça plante toujours avec la même erreur... et c'est super galère pour choper une session valide sur Katacoda...
@Dougniel tu as bien poussé le fix sur `optnc/api-partenaires-mobilis:stable` ?

**Comment by Dougniel** [comment]
> Je viens de tester sur katacoda mais ça plante toujours avec la même erreur... et c'est super galère pour choper une session valide sur Katacoda...
> @Dougniel tu as bien poussé le fix sur `optnc/api-partenaires-mobilis:stable` ?

Le build tombe en erreur lors de la génération de l'image #122, j'essaie de faire du forcing sur un malentendu ça peut peut-être passer

**Comment by adriens** [comment]
> j'essaie de faire du forcing sur un malentendu ça peut peut-être passer

😆

**Comment by adriens** [comment]
I think it's fixed now @Dougniel :+1: 
If yes, please close the issue :pray:

**Comment by adriens** [comment]
:zap:
