### ISSUE TITLE
🚨 Supprimer '.' des noms de query parameters 🚨 

### ISSUE THREAD

**Issue by adriens** [opt-nc/api-partenaires-mobilis#140]
- [x] Changement d'API : Modifier le code source ainsi que la documentation, releaser une version majeure
- [x] https://github.com/opt-nc/katacoda-opt-labs/issues/25

Ca me bloque pour implémenter les queryParamter sur le porail d'APIs : 

![image](https://user-images.githubusercontent.com/5235127/160951506-be82f26a-78fe-428c-93ec-22653be8d616.png)

**Comment by Dougniel** [comment]
Ah bon, c'est RapidAPI qui fixe là loi 😅 ? Il va falloir que je change tous les scénarios des Katacoda aussi

**Comment by adriens** [comment]
> que je change tous les scénarios des Katacoda aussi

yep j'y ai pensé aussi 💩

**Comment by adriens** [comment]
`w3` quoi ? Le trucs avec le badge html valide ?

**Comment by adriens** [comment]
Ok, je vais demander un redéploiement cloud avec cette version afin de pouvoir faire le nécessaire sur le marketplace :+1:
