### ISSUE TITLE
Implémenter /management/health

### ISSUE THREAD

**Issue by adriens** [opt-nc/api-partenaires-mobilis#160]
```
# Run current stable image in background
docker run -d --rm -p 8080:8080 --name health optnc/api-partenaires-mobilis:stable
# Ask actuator
http :8080/management/health
# Kill all containers
docker kill health
```

![image](https://user-images.githubusercontent.com/5235127/168169958-ebf4c209-8179-4605-b499-62db572fe14b.png)

**Comment by Dougniel** [comment]
https://github.com/opt-nc/GLIA/issues/582#issuecomment-1126570555, déjà sur `/actuator/health`
