### ISSUE TITLE
Organiser démo interne

### ISSUE THREAD

**Issue by adriens** [opt-nc/api-partenaires-mobilis#22]

**Comment by Dougniel** [comment]
Déjà fait sur place et de maintes reprises, notamment via https://github.com/opt-nc/GLIA/issues/179

**Comment by adriens** [comment]
Yep, dès qu eje peux je fais la démo DSI

**Comment by Dougniel** [comment]
Ah donc je n'avais pas compris, je croyais interne GLIA, tu voulais dire interne OPT ? Du coup je réouvre ?

**Comment by adriens** [comment]
Non non c'est parfait. j'ai tout un train de démos à envoyer.
