### ISSUE TITLE
Configurer le Code Scanning

### ISSUE THREAD

**Issue by adriens** [opt-nc/api-partenaires-mobilis#23]
https://docs.github.com/en/code-security/secure-coding/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning

**Comment by Dougniel** [comment]
<img width="1477" alt="image" src="https://user-images.githubusercontent.com/39691264/160838420-4fb8668e-943e-4cc2-9c37-98bcd1a2d992.png">

**Comment by adriens** [comment]
:zap:
